"use server";

import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

export async function generateCoverLetter(data) {
  /*
    Expected data:
    {
      jobTitle: "Software Engineer",
      companyName: "Tech Solutions Pvt. Ltd.",
      jobDescription: "We are looking for...",
      industry: "Information Technology",
      experience: "2 years",
      skills: ["Python", "Machine Learning", "SQL"],
      bio: "A passionate developer with experience building AI-driven apps."
    }
  */

  const prompt = `
  You are a professional HR writing assistant. Write a **complete, ready-to-send cover letter** for the following candidate and job details.

  🧑‍💼 **Candidate Details:**
  - Industry: ${data.industry || "Not specified"}
  - Years of Experience: ${data.experience || "Not specified"}
  - Key Skills: ${data.skills?.join(", ") || "Not specified"}
  - Background: ${data.bio || "Not provided"}

  💼 **Job Details:**
  - Position: ${data.jobTitle || "Not specified"}
  - Company: ${data.companyName || "Not specified"}
  - Description: ${data.jobDescription || "Not provided"}

  ✍️ **Instructions:**
  - Follow a professional **business letter format** (with header, greeting, body, and closing).
  - Use an enthusiastic yet formal tone.
  - Highlight the candidate’s most relevant skills and achievements.
  - Mention the company name naturally in the letter.
  - Relate the candidate’s background to the company’s goals and the job description.
  - Keep it **concise (under 400 words)**.
  - Return the final answer **in markdown format** — ready to render in a web app.
  - Do not include explanations or notes, only the formatted letter.

  Example structure (for reference only):
  ---
  **[Candidate Name]**  
  [Email] | [Phone] | [LinkedIn]  
  [Date]

  **Dear [Hiring Manager’s Name],**  
  [Opening paragraph introducing yourself and role applied for.]  
  [Body paragraph showing experience, achievements, and enthusiasm.]  
  [Closing paragraph with thanks and interest in interview.]

  **Sincerely,**  
  [Candidate Name]
  ---
  `;

  try {
    const result = await model.generateContent(prompt);
    const output = result.response.text().trim();
    if (!output) throw new Error("No content generated by model");
    return output;
  } catch (error) {
    console.error("Error generating cover letter:", error);
    throw new Error("Failed to generate cover letter");
  }
}
